### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by michaelhly** [blobs-lol/blobs-nft#2]
![unnamed](https://user-images.githubusercontent.com/24895862/200158698-bc87407a-e257-42e5-9165-7391d2b41be8.png)

**Comment by michaelhly** [comment]
<img width="284" alt="Screen Shot 2022-11-05 at 10 59 21 PM" src="https://user-images.githubusercontent.com/24895862/200158718-178a1113-952b-4aae-9118-fca4a40965d5.png">

**Comment by gqln** [comment]
![Icon](https://user-images.githubusercontent.com/18605279/200744130-e7ffae5f-f8b1-4a50-9341-38df295b0dc7.png)
